version: "3.6"

services:

  powerboard-extension:
    build:
      context: .
      dockerfile: extension/Dockerfile
    restart: always
    ports:
      - 8082:8082
    environment:
      - "POWERBOARD_INTEGRATION_CONFIG=xxxxxx"

  powerboard-notification:
    build:
      context: .
      dockerfile: notification/Dockerfile
    restart: always
    ports:
      - 8443:8443
    environment:
      - "POWERBOARD_INTEGRATION_CONFIG=xxxxxx"
